=head1 NAME

Padre::Manual::Translating - Guide to translating Padre

=head1 DESCRIPTION

This is the Padre Translation Guide.

My apologies for the small amount of information currently available in
this document. That will be changed.

=head2 Translation Files

Currently we are using Wx::gettext so we have a po file for each additional
language in the share/locale/ directory.

Before release the /tools/release.pl script generates .mo files using

  msgfmt -o share/locale/de.mo share/locale/de.po
