=head1 NAME

Padre::Manual - The Primary Padre Documentation



=head1 DESCRIPTION

This is a stub for what will eventually become the Padre manual.

Currently this serves as a launch point for each of the child documents
that make up the nascent "manual".


=head2 Padre Developer Guide

If you would like to help improve Padre see L<Padre::Manual::Hacking>
for information on checking out the Padre source code, how to work with
it, file bugs, and on.


=head2 Padre Translation Guild

If you would like to translate Padre into your local language, see the
online documentation for more details.

L<http://padre.perlide.org/wiki/TranslationIntro>

TO BE COMPLETED

