package Padre::Wx::FBP::CPAN;

## no critic

# This module was generated by Padre::Plugin::FormBuilder::Perl.
# To change this module edit the original .fbp file and regenerate.
# DO NOT MODIFY THIS FILE BY HAND!

use 5.008;
use strict;
use warnings;
use Padre::Wx ();
use Padre::Wx::Role::Main ();
use Padre::Wx::HtmlWindow ();

our $VERSION = '0.91';
our @ISA     = qw{
	Padre::Wx::Role::Main
	Wx::Panel
};

sub new {
	my $class  = shift;
	my $parent = shift;

	my $self = $class->SUPER::new(
		$parent,
		-1,
		Wx::DefaultPosition,
		[ 235, 530 ],
		Wx::TAB_TRAVERSAL,
	);

	$self->{m_notebook} = Wx::Notebook->new(
		$self,
		-1,
		Wx::DefaultPosition,
		Wx::DefaultSize,
	);

	$self->{search_panel} = Wx::Panel->new(
		$self->{m_notebook},
		-1,
		Wx::DefaultPosition,
		Wx::DefaultSize,
		Wx::TAB_TRAVERSAL,
	);

	$self->{search} = Wx::TextCtrl->new(
		$self->{search_panel},
		-1,
		"",
		Wx::DefaultPosition,
		Wx::DefaultSize,
	);

	Wx::Event::EVT_TEXT(
		$self,
		$self->{search},
		sub {
			shift->on_search_text(@_);
		},
	);

	$self->{list} = Wx::ListCtrl->new(
		$self->{search_panel},
		-1,
		Wx::DefaultPosition,
		Wx::DefaultSize,
		Wx::LC_REPORT | Wx::LC_SINGLE_SEL,
	);

	Wx::Event::EVT_LIST_COL_CLICK(
		$self,
		$self->{list},
		sub {
			shift->on_list_column_click(@_);
		},
	);

	Wx::Event::EVT_LIST_ITEM_SELECTED(
		$self,
		$self->{list},
		sub {
			shift->on_list_item_selected(@_);
		},
	);

	$self->{recent_panel} = Wx::Panel->new(
		$self->{m_notebook},
		-1,
		Wx::DefaultPosition,
		Wx::DefaultSize,
		Wx::TAB_TRAVERSAL,
	);

	$self->{recent_list} = Wx::ListCtrl->new(
		$self->{recent_panel},
		-1,
		Wx::DefaultPosition,
		Wx::DefaultSize,
		Wx::LC_REPORT | Wx::LC_SINGLE_SEL,
	);

	Wx::Event::EVT_LIST_COL_CLICK(
		$self,
		$self->{recent_list},
		sub {
			shift->on_list_column_click(@_);
		},
	);

	Wx::Event::EVT_LIST_ITEM_SELECTED(
		$self,
		$self->{recent_list},
		sub {
			shift->on_list_item_selected(@_);
		},
	);

	$self->{show_recent} = Wx::Button->new(
		$self->{recent_panel},
		-1,
		Wx::gettext("Refresh"),
		Wx::DefaultPosition,
		Wx::DefaultSize,
	);

	Wx::Event::EVT_BUTTON(
		$self,
		$self->{show_recent},
		sub {
			shift->on_show_recent_click(@_);
		},
	);

	$self->{doc} = Padre::Wx::HtmlWindow->new(
		$self,
		-1,
		Wx::DefaultPosition,
		Wx::DefaultSize,
		Wx::STATIC_BORDER,
	);
	$self->{doc}->SetBackgroundColour(
		Wx::Colour->new( 253, 252, 187 )
	);

	$self->{synopsis} = Wx::Button->new(
		$self,
		-1,
		Wx::gettext("Insert Synopsis"),
		Wx::DefaultPosition,
		Wx::DefaultSize,
	);

	Wx::Event::EVT_BUTTON(
		$self,
		$self->{synopsis},
		sub {
			shift->on_synopsis_click(@_);
		},
	);

	$self->{changes} = Wx::Button->new(
		$self,
		-1,
		Wx::gettext("Show Changes"),
		Wx::DefaultPosition,
		Wx::DefaultSize,
	);

	Wx::Event::EVT_BUTTON(
		$self,
		$self->{changes},
		sub {
			shift->on_changes_click(@_);
		},
	);

	$self->{install} = Wx::Button->new(
		$self,
		-1,
		Wx::gettext("Install"),
		Wx::DefaultPosition,
		Wx::DefaultSize,
	);

	Wx::Event::EVT_BUTTON(
		$self,
		$self->{install},
		sub {
			shift->on_install_click(@_);
		},
	);

	my $search_sizer = Wx::BoxSizer->new(Wx::HORIZONTAL);
	$search_sizer->Add( $self->{search}, 1, Wx::ALIGN_CENTER_VERTICAL, 0 );

	my $search_panel_sizer = Wx::BoxSizer->new(Wx::VERTICAL);
	$search_panel_sizer->Add( $search_sizer, 0, Wx::ALL | Wx::EXPAND, 1 );
	$search_panel_sizer->Add( $self->{list}, 1, Wx::ALL | Wx::EXPAND, 1 );

	$self->{search_panel}->SetSizerAndFit($search_panel_sizer);
	$self->{search_panel}->Layout;

	my $recent_panel_sizer = Wx::BoxSizer->new(Wx::VERTICAL);
	$recent_panel_sizer->Add( $self->{recent_list}, 1, Wx::ALL | Wx::EXPAND, 5 );
	$recent_panel_sizer->Add( $self->{show_recent}, 0, Wx::ALIGN_CENTER | Wx::ALL, 1 );

	$self->{recent_panel}->SetSizerAndFit($recent_panel_sizer);
	$self->{recent_panel}->Layout;

	$self->{m_notebook}->AddPage( $self->{search_panel}, Wx::gettext("Search"), 1 );
	$self->{m_notebook}->AddPage( $self->{recent_panel}, Wx::gettext("Recent"), 0 );

	my $button_row_1 = Wx::BoxSizer->new(Wx::HORIZONTAL);
	$button_row_1->Add( 2, 0, 0, 0, 0 );
	$button_row_1->Add( $self->{synopsis}, 0, Wx::ALL | Wx::EXPAND, 2 );
	$button_row_1->Add( $self->{changes}, 0, Wx::ALL | Wx::EXPAND, 2 );

	my $button_row_2 = Wx::BoxSizer->new(Wx::HORIZONTAL);
	$button_row_2->Add( 5, 0, 0, 0, 5 );
	$button_row_2->Add( $self->{install}, 0, Wx::ALIGN_CENTER, 2 );
	$button_row_2->Add( 0, 0, 1, Wx::EXPAND, 5 );

	my $button_sizer = Wx::BoxSizer->new(Wx::VERTICAL);
	$button_sizer->Add( $button_row_1, 0, Wx::EXPAND, 5 );
	$button_sizer->Add( $button_row_2, 0, Wx::EXPAND, 5 );

	my $main_sizer = Wx::BoxSizer->new(Wx::VERTICAL);
	$main_sizer->Add( $self->{m_notebook}, 1, Wx::EXPAND | Wx::ALL, 5 );
	$main_sizer->Add( $self->{doc}, 1, Wx::ALL | Wx::EXPAND, 1 );
	$main_sizer->Add( $button_sizer, 0, Wx::ALL | Wx::EXPAND, 2 );

	$self->SetSizer($main_sizer);
	$self->Layout;

	return $self;
}

sub on_search_text {
	$_[0]->main->error('Handler method on_search_text for event search.OnText not implemented');
}

sub on_list_column_click {
	$_[0]->main->error('Handler method on_list_column_click for event list.OnListColClick not implemented');
}

sub on_list_item_selected {
	$_[0]->main->error('Handler method on_list_item_selected for event list.OnListItemSelected not implemented');
}

sub on_show_recent_click {
	$_[0]->main->error('Handler method on_show_recent_click for event show_recent.OnButtonClick not implemented');
}

sub on_synopsis_click {
	$_[0]->main->error('Handler method on_synopsis_click for event synopsis.OnButtonClick not implemented');
}

sub on_changes_click {
	$_[0]->main->error('Handler method on_changes_click for event changes.OnButtonClick not implemented');
}

sub on_install_click {
	$_[0]->main->error('Handler method on_install_click for event install.OnButtonClick not implemented');
}

1;

# Copyright 2008-2011 The Padre development team as listed in Padre.pm.
# LICENSE
# This program is free software; you can redistribute it and/or
# modify it under the same terms as Perl 5 itself.

