package Padre::Wx::FBP::FindInFiles::Output;

## no critic

# This module was generated by Padre::Plugin::FormBuilder::Perl.
# To change this module edit the original .fbp file and regenerate.
# DO NOT MODIFY THIS FILE BY HAND!

use 5.008;
use strict;
use warnings;
use Padre::Wx ();
use Padre::Wx::Role::Main ();
use Padre::Wx::TreeCtrl ();

our $VERSION = '0.01';
our @ISA     = qw{
	Padre::Wx::Role::Main
	Wx::Panel
};

sub new {
	my $class  = shift;
	my $parent = shift;

	my $self = $class->SUPER::new(
		$parent,
		-1,
		Wx::DefaultPosition,
		[ 500, 300 ],
		Wx::TAB_TRAVERSAL,
	);

	$self->{repeat} = Wx::Button->new(
		$self,
		-1,
		Wx::gettext("Repeat"),
		Wx::DefaultPosition,
		Wx::DefaultSize,
	);

	$self->{expand_all} = Wx::Button->new(
		$self,
		-1,
		Wx::gettext("Expand all"),
		Wx::DefaultPosition,
		Wx::DefaultSize,
	);

	$self->{collapse_all} = Wx::Button->new(
		$self,
		-1,
		Wx::gettext("Collapse all"),
		Wx::DefaultPosition,
		Wx::DefaultSize,
	);

	$self->{tree} = Padre::Wx::TreeCtrl->new(
		$self,
		-1,
		Wx::DefaultPosition,
		Wx::DefaultSize,
		Wx::TR_FULL_ROW_HIGHLIGHT | Wx::TR_HAS_BUTTONS | Wx::TR_SINGLE,
	);

	my $button_sizer = Wx::BoxSizer->new(Wx::HORIZONTAL);
	$button_sizer->Add( $self->{repeat}, 0, Wx::ALL, 5 );
	$button_sizer->Add( $self->{expand_all}, 0, Wx::ALL, 5 );
	$button_sizer->Add( $self->{collapse_all}, 0, Wx::ALL, 5 );

	my $main_sizer = Wx::BoxSizer->new(Wx::VERTICAL);
	$main_sizer->Add( $button_sizer, 0, 0, 5 );
	$main_sizer->Add( $self->{tree}, 1, Wx::ALL | Wx::EXPAND, 5 );

	$self->SetSizer($main_sizer);
	$self->Layout;

	return $self;
}

1;

# Copyright 2008-2011 The Padre development team as listed in Padre.pm.
# LICENSE
# This program is free software; you can redistribute it and/or
# modify it under the same terms as Perl 5 itself.

